### ISSUE TITLE
Include error boundaries to make the error handling smooth and non-breaking flow

### ISSUE THREAD

**Issue by shirish-heller** [shirish-heller/workflow-record-and-walkthrough#6]

**Comment by sowmiyamuthuraman** [comment]
@shirish-heller I would like to work on this! does the error boundary should simply log the error to the service or we should redirect the user to a custom error page

**Comment by shirish-heller** [comment]
Hey,

Thanks for taking interest in this issue. I have added you as a
collaborator. Kindly accept the invitation
https://github.com/shirish-heller/workflow-record-and-walkthrough/invitations

*So this is the problem at hand:-*
We are a supporting tool that helps other products. In no case should the
main products flow/working be affected due to a issue with our tool. That's
why we need error boundaries.
We need to figure out the most error prone places and wrap them in error
boundaries. So when something in our app breaks we just show a popup saying
something went wrong, log that error and maybe reset our tool's state to
the initial state.
(One example, After we record a workflow and save it and the customer plays
that workflow...our package tries to find the UI element that is recorded
in the 2nd step so that it can highlight it...Lets say that our code cannot
find that element on UI
In that case we need error boundaries to handle this scenario for us. We
can tell the customer that there is some problem with this workflow and the
team is working on this.)


This is my take on this, I would be happy to listen to any ideas you have.
We can even connect on hangouts if you need code walkthrough or some other
clarifications.
I think this package has great potential and there is nothing like this in
the market. We can make this big :)

**Comment by shirish-heller** [comment]
closing
